class CoquiWebhook {
  final String id;
  final String name;
  final String? description;
  final String source;
  final String secret;
  final String promptTemplate;
  final String role;
  final String? profile;
  final int maxIterations;
  final bool enabled;
  final String? eventFilter;
  final String? createdBy;
  final DateTime? lastTriggeredAt;
  final int triggerCount;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  const CoquiWebhook({
    required this.id,
    required this.name,
    required this.description,
    required this.source,
    required this.secret,
    required this.promptTemplate,
    required this.role,
    required this.profile,
    required this.maxIterations,
    required this.enabled,
    required this.eventFilter,
    required this.createdBy,
    required this.lastTriggeredAt,
    required this.triggerCount,
    required this.createdAt,
    required this.updatedAt,
  });

  factory CoquiWebhook.fromJson(Map<String, dynamic> json) {
    return CoquiWebhook(
      id: json['id'] as String? ?? '',
      name: json['name'] as String? ?? '',
      description: json['description'] as String?,
      source: json['source'] as String? ?? 'generic',
      secret: json['secret'] as String? ?? '',
      promptTemplate: json['prompt_template'] as String? ?? '',
      role: json['role'] as String? ?? 'orchestrator',
      profile: json['profile'] as String?,
      maxIterations: _coerceInt(json['max_iterations'], fallback: 48),
      enabled: _coerceBool(json['enabled'], fallback: true),
      eventFilter: json['event_filter'] as String?,
      createdBy: json['created_by'] as String?,
      lastTriggeredAt: _parseDateTime(json['last_triggered_at']),
      triggerCount: _coerceInt(json['trigger_count']),
      createdAt: _parseDateTime(json['created_at']),
      updatedAt: _parseDateTime(json['updated_at']),
    );
  }

  bool get hasProfile => profile != null && profile!.isNotEmpty;

  bool get hasDescription => description != null && description!.isNotEmpty;

  bool get hasEventFilter => eventFilter != null && eventFilter!.isNotEmpty;

  bool get hasActivity => lastTriggeredAt != null || triggerCount > 0;

  bool get isSecretMasked => secret.contains('*');

  String get sourceLabel => switch (source) {
        'github' => 'GitHub',
        'slack' => 'Slack',
        _ => 'Generic',
      };

  String get statusLabel => enabled ? 'Enabled' : 'Disabled';

  String get secretLabel => secret.isEmpty ? 'Generated by server' : secret;

  CoquiWebhook copyWith({
    String? name,
    String? description,
    String? source,
    String? secret,
    String? promptTemplate,
    String? role,
    String? profile,
    int? maxIterations,
    bool? enabled,
    String? eventFilter,
    String? createdBy,
    DateTime? lastTriggeredAt,
    int? triggerCount,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return CoquiWebhook(
      id: id,
      name: name ?? this.name,
      description: description ?? this.description,
      source: source ?? this.source,
      secret: secret ?? this.secret,
      promptTemplate: promptTemplate ?? this.promptTemplate,
      role: role ?? this.role,
      profile: profile ?? this.profile,
      maxIterations: maxIterations ?? this.maxIterations,
      enabled: enabled ?? this.enabled,
      eventFilter: eventFilter ?? this.eventFilter,
      createdBy: createdBy ?? this.createdBy,
      lastTriggeredAt: lastTriggeredAt ?? this.lastTriggeredAt,
      triggerCount: triggerCount ?? this.triggerCount,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}

DateTime? _parseDateTime(Object? value) {
  if (value is! String || value.isEmpty) return null;
  return DateTime.tryParse(value);
}

int _coerceInt(Object? value, {int fallback = 0}) {
  if (value is int) return value;
  if (value is num) return value.toInt();
  if (value is String) return int.tryParse(value) ?? fallback;
  return fallback;
}

bool _coerceBool(Object? value, {bool fallback = false}) {
  if (value is bool) return value;
  if (value is num) return value != 0;
  if (value is String) {
    return value == '1' || value.toLowerCase() == 'true';
  }
  return fallback;
}
